spring:
  profiles:
    active: local
  messages:
    encoding: UTF-8
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  datasource:
    driver-class-name: org.h2.Driver
